### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 4troDev** [ZerioDev/DiscordTickets#3]
is there a way to have tickets open under a specify category?

**Comment by KartikeSingh** [comment]
yes, just save the id of that category and provide that category as a parent channel.
for example
```js
guild.channels.create("name",{
    parent:guild.channels.cache.get("catgeory-id");
})
```

**Comment by BlobDeveloper** [comment]
> yes, just save the id of that category and provide that category as a parent channel.
> for example
> ```js
> guild.channels.create("name",{
>     parent:guild.channels.cache.get("catgeory-id");
> })
> ```

Or
```js
parent: 'category id',
```
